// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdbNPAfV0bUy6VmAcATu5Ma01aK6-CjNU',
    appId: '1:107497204327:web:421b4d69708afa7f4c02c2',
    messagingSenderId: '107497204327',
    projectId: 'tytapp-9571e',
    authDomain: 'tytapp-9571e.firebaseapp.com',
    storageBucket: 'tytapp-9571e.appspot.com',
    measurementId: 'G-7N4ZTVJBMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1quYdybygnj65fyLRt_ATQW1GWCAcd58',
    appId: '1:107497204327:android:516f1b09163fbaf94c02c2',
    messagingSenderId: '107497204327',
    projectId: 'tytapp-9571e',
    storageBucket: 'tytapp-9571e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKVObeLv6uqbhgCAx20pFtNEYzJ2zlUO0',
    appId: '1:107497204327:ios:a06f427cd264064f4c02c2',
    messagingSenderId: '107497204327',
    projectId: 'tytapp-9571e',
    storageBucket: 'tytapp-9571e.appspot.com',
    androidClientId: '107497204327-m08bt0r2feriebr3og65skhgnfgpoi9h.apps.googleusercontent.com',
    iosClientId: '107497204327-9o7f4f8emllia47cnkv78boer8nl5s60.apps.googleusercontent.com',
    iosBundleId: 'com.japps.tytapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKVObeLv6uqbhgCAx20pFtNEYzJ2zlUO0',
    appId: '1:107497204327:ios:a06f427cd264064f4c02c2',
    messagingSenderId: '107497204327',
    projectId: 'tytapp-9571e',
    storageBucket: 'tytapp-9571e.appspot.com',
    androidClientId: '107497204327-m08bt0r2feriebr3og65skhgnfgpoi9h.apps.googleusercontent.com',
    iosClientId: '107497204327-9o7f4f8emllia47cnkv78boer8nl5s60.apps.googleusercontent.com',
    iosBundleId: 'com.japps.tytapp',
  );
}
